### ISSUE TITLE
Allow EntityViewSettingProcessor to return subtyped EntityViewSetting

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#806] opened 2019-05-17 13:12 UTC
Change EntityViewSettingProcessor interface to
```java
public interface EntityViewSettingProcessor<T> {

    EntityViewSetting<? extends T, ?> acceptEntityViewSetting(EntityViewSetting<T, ?> setting);
}
```

**Comment by beikov** [comment] 2019-05-17 13:26
Duplicate of https://github.com/Blazebit/blaze-persistence/issues/713

**Closed by beikov** 2019-05-17 13:26 UTC
Labels: enhancement, spring-data
