### ISSUE TITLE
how to forbid auto add select columns on group by 

### ISSUE THREAD

**Issue by luyuanx2** [Blazebit/blaze-persistence#1224] opened 2020-12-01 10:00 UTC
![image](https://user-images.githubusercontent.com/26129033/100725349-e1ec4680-33fe-11eb-8884-a1f86e785f00.png)
This is auto add，I hope group by only `resourcepo0_.id`

**Comment by beikov** [comment] 2020-12-01 10:03
Hi,

you can control this through the following configuration property: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#IMPLICIT_GROUP_BY_FROM_SELECT

Which version are you using? Since `GROUP_CONCAT` is actually an aggregate function, it should not end up in the group by clause. We actually have tests for his so I'm surprised to see this happening. Could you also share some of the code you are using so that we can try to reproduce this issue?

**Comment by luyuanx2** [comment] 2020-12-01 10:14
> it should not end up in the group by clause. We actually have tests for his so I'm surprised to see this happening.

yes, the actual error is `group_cancat` can't use in group by clause
![image](https://user-images.githubusercontent.com/26129033/100727286-ff221480-3400-11eb-9af3-9b703d22dd1e.png)

**Comment by luyuanx2** [comment] 2020-12-01 10:18
> Hi,
> 
> you can control this through the following configuration property: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#IMPLICIT_GROUP_BY_FROM_SELECT
> 
> Which version are you using? Since `GROUP_CONCAT` is actually an aggregate function, it should not end up in the group by clause. We actually have tests for this so I'm surprised to see this happening. Could you also share some of the code you are using so that we can try to reproduce this issue?

part of my code，`group_concat_distinct` is my custom function
![image](https://user-images.githubusercontent.com/26129033/100727707-938c7700-3401-11eb-886a-da81b6a10245.png)

**Comment by jwgmeligmeyling** [comment] 2020-12-01 10:31
You need to register the custom function as aggregate function for implicit group by to work properly. Blaze-Persistence by the way has its own implementation of `group_concat` (also the distinct version) which is already registered as an aggregate function.

To use this in the QueryDSL integration you use: [`JPQLNextExpressions.groupBy(groups.name)`](https://github.com/Blazebit/blaze-persistence/blob/master/integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java#L1002-L1004) or for distinct [`JPQLNextExpressions.groupBy(true, groups.name)`](https://github.com/Blazebit/blaze-persistence/blob/master/integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java#L1018-L1029).

**Comment by beikov** [comment] 2020-12-01 10:32
Interesting, can we maybe support this string template stuff somehow @jwgmeligmeyling ?

**Comment by jwgmeligmeyling** [comment] 2020-12-01 10:36
We do support the string template stuff, as long as the function used is the same one we have implemented ;-) The problem is the user uses his own `group_concat_distinct` instead of `GROUP_CONCAT ( ('DISTINCT' )? , string (, 'SEPARATOR', separatorString)? (, 'ORDER BY', ( orderByExpr, ( 'ASC' | 'DESC' ) )+ ) )`

**Comment by beikov** [comment] 2020-12-01 10:43
Since this can be solved by using the builtin function, I'll close this.

**Closed by beikov** 2020-12-01 10:43 UTC
Labels: component: QueryDSL, question

**Comment by jwgmeligmeyling** [comment] 2020-12-01 13:20
@luyuanx2 did it work for you?
