### ISSUE TITLE
Cannot use bind parameters with collection DML queries

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#777] opened 2019-04-16 12:37 UTC
Hibernate throws:
```
java.lang.IllegalArgumentException: org.hibernate.QueryException: Parameters are only supported in SELECT clauses when used as part of a INSERT INTO DML statement
```

**Comment by beikov** [comment] 2019-04-17 15:48
Duplicate of #671

**Closed by beikov** 2019-04-17 15:48 UTC
Labels: bug, core
