### ISSUE TITLE
unknown ClassCastException

### ISSUE THREAD

**Issue by yushengruohui** [Blazebit/blaze-persistence#1885] opened 2024-04-04 05:23 UTC
### Description

As Querydsl recommends the use of blaze-persistence after version 5.0.0, I integrated it. Some simple single-table queries worked fine, but when I tried to execute the following query, I encountered a ClassCastException.

### Steps to reproduce

code：
```
        QBdpDept t1 = QBdpDept.bdpDept;
        QDeptRole t2 = QDeptRole.deptRole;
        String keyword = dto.getKeyword();

        BooleanBuilder builder = new BooleanBuilder();
        builder.and(t2.id.isNull());
        builder.and(t2.roleId.eq(dto.getRoleId()));

        var query = new BlazeJPAQuery<>(entityManager, criteriaBuilderFactory)
                .select(Projections.bean(RoleDeptVo.class, t2.id, t2.deptId, t1.pid, t1.deptName, t1.deptCode))
                .from(t1)
                .leftJoin(t2)
                .on(t2.deptId.eq(t1.id))
                .where(builder)
                .orderBy(t1.id.desc())
                .offset(dto.getOffset())
                .limit(dto.getPageSize());
        long count = query.fetchCount();
```

exception log：
```
java.lang.ClassCastException : class jdk.proxy2.$Proxy233 cannot be cast to class org.hibernate.query.sqm.internal.QuerySqmImpl (jdk.proxy2.$Proxy233 is in module jdk.proxy2 of loader 'app'; org.hibernate.query.sqm.internal.QuerySqmImpl is in unnamed module of loader 'app')
        at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.getSql(HibernateExtendedQuerySupport.java:221)
        at com.blazebit.persistence.impl.query.CustomQuerySpecification.<init>(CustomQuerySpecification.java:107)
        at com.blazebit.persistence.impl.AbstractFullQueryBuilder.getCountQuery(AbstractFullQueryBuilder.java:715)
        at com.blazebit.persistence.impl.AbstractFullQueryBuilder.getCountQuery(AbstractFullQueryBuilder.java:642)
        at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:173)
        at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchCount(AbstractBlazeJPAQuery.java:261)
```

maven dependency：
```
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-integration-querydsl-expressions-jakarta</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-core-api-jakarta</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-core-impl-jakarta</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-integration-hibernate-6.2</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>runtime</scope>
        </dependency>
```

### Environment
Version: 1.6.11
JPA-Provider: Hibernate 6.4.1
DBMS: Postgres 16
springboot: 3.2.2
jdk: 17

**Comment by beikov** [comment] 2024-04-08 10:59
Hi and thanks for reporting this issue. It seems like something (Spring ORM integration?) creates a proxy for a created query which then fails to unwrap correctly. Do you think you could provide a reproducer for this?

**Comment by jwgmeligmeyling** [comment] 2024-04-08 11:04
IIRC Projections.bean is a factory expression that has to be used with a query transformer (query().transform(Projections.bean(…)) and cannot be used as a select expression directly. I don’t think this is specific to the integration, does it work in standard Querydsl?

**Comment by yushengruohui** [comment] 2024-04-08 11:35
> IIRC Projections.bean is a factory expression that has to be used with a query transformer (query().transform(Projections.bean(…)) and cannot be used as a select expression directly. I don’t think this is specific to the integration, does it work in standard Querydsl?

In Querydsl, this code can run normally. It's only after switching to BlazeJPAQuery that I encountered this issue.

**Comment by yushengruohui** [comment] 2024-04-08 11:44
> Hi and thanks for reporting this issue. It seems like something (Spring ORM integration?) creates a proxy for a created query which then fails to unwrap correctly. Do you think you could provide a reproducer for this?

I apologize, but it's not convenient for me to provide the complete code from the team project.

**Comment by beikov** [comment] 2024-04-08 12:41
> > Hi and thanks for reporting this issue. It seems like something (Spring ORM integration?) creates a proxy for a created query which then fails to unwrap correctly. Do you think you could provide a reproducer for this?
> 
> I apologize, but it's not convenient for me to provide the complete code from the team project.

Sure, that's fine, but maybe you can create a small reproducer application e.g. based on our [quickstarts](https://github.com/Blazebit/blaze-persistence?tab=readme-ov-file#quickstart)?

**Comment by wangguofeng1923** [comment] 2024-04-26 05:29
[spring-examples.zip](https://github.com/Blazebit/blaze-persistence/files/15125732/spring-examples.zip)
i reproduced this issue too, and attacted my demo application

**Comment by beikov** [comment] 2024-05-06 13:56
I just checked the reproducer and this seems to be an issue with Spring Data. A proxy created by `SharedEntityManagerCreator` is used as `EntityManager`, which in turn creates a proxy for queries. This is where things go wrong, but not sure why that pops up only just now. Seems the code was like this for a long time.

**Comment by beikov** [comment] 2024-05-06 13:58
One possible workaround is to mark the method as `@Transactional` to use the proper `EntityManager` and not this Spring Data proxy

**Comment by beikov** [comment] 2024-05-06 14:05
Also see https://github.com/spring-projects/spring-framework/issues/32766

**Comment by jwgmeligmeyling** [comment] 2024-05-06 15:26
We can probably close this issue then right? Or do you see a way to workaround this limitation that we can implement?

**Comment by beikov** [comment] 2024-05-06 15:58
Yes, I'm going to close this issue.

**Closed by beikov** 2024-05-06 15:58 UTC
Labels: kind: bug, workaround available, component: spring-data, worth: high
