### ISSUE TITLE
Paginated CB don't work with aggregates, unique order check doesn't account for (implicit) group by's

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#568] opened 2018-05-15 13:19 UTC
Pagined criteria builders do not work with aggregate functions, unique check does not account for (implicit) group by's. So even though a path expression is unique in the query result, ExpressionUtils.isUnique will be invoked and return false as the join column is not unique.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by JWGmeligMeyling** [comment] 2018-05-15 13:31
Ah I just see that paginated queries don't support group by's anyway, it's just that it doesn't report it for implicit group by's. Why aren't group by queries supported?

**Comment by beikov** [comment] 2018-05-15 13:48
Group bys aren't supported yet because we weren't able to figure out how to do it correctly yet and didn't have the need so far. Implicit group bys mostly work and are a way to go in the meantime, but I agree we should add proper support for group by at some point.

**Comment by JWGmeligMeyling** [comment] 2018-05-15 14:35
My use case is that I have an entityview with an aggregrate function and hence some implicit group by's, and I'd like to paginate that. It seems pretty easily to paginate any query as long as the order columns are unique (which means they are either unique by the current definition, that is, their join column is unique, or they are part of the group by clause of the query which obviously indicates it is unique in the query result. I've now worked around it by creating my count and list query myself (had to work around #570 to get this done). It seems in order to support paginated aggregate queries, we also need to fix `getCountQuery` on `CriteriaBuilder`, as it does not take the grouping columns into account and hence returns the ungrouped row count (which is usually too high). I'm not sure though whether aggregate queries still work well with keyset pagination, and currently the `PagedList` requires a `KeysetPage` as well. As I am not using that I could easily work around it, so I didn't look into the internals to see how easily that could be adjusted to aggregate functions as well.

I think it would be nice in general to support group by clauses in general, so we could rephase this issue to just add support for that any time soon. However if this turns out to be difficult I think it would be nice to add the same type of exception for queries with implicit group by's as we currently have for trying to use pagination with queries that specify a group by clause.

**Comment by beikov** [comment] 2018-07-25 17:31
Closing this since it's kind of a duplicate of #194 which will be part of 1.3.0

**Closed by beikov** 2018-07-25 17:31 UTC
Labels: bug, core, enhancement
