### ISSUE TITLE
group by + having count + DISTINCT does not work

### ISSUE THREAD

**Issue by alohaaloha** [Blazebit/blaze-persistence#1374] opened 2021-10-23 09:13 UTC
### Description

Calling following: 
```
query
.distinct()
.where(field.in(values))
.groupBy(id)
.groupBy(groupByField)
.having(field.countDistinct().goe(1))
```
does not returns same results as generated sql from same code does. 

### Expected behavior

Expected is to get actual response that you get when you manually execute generated query.

### Actual behavior

- In query dsl 4.x version - response is empty list.
- In query dsl 5.x - there is an exception: 

`java.lang.NoSuchFieldError: hints at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:234)`

### Steps to reproduce

When executing following:
```
query
.distinct()
.where(field.in(values))
.groupBy(id)
.groupBy(groupByField)
.having(field.count().goe(1))
```

Generated query when inspecting is: 
```
select distinct entity
where field in ( ... )
group by id, groupByField
having count(field) >= 1
```

and there are returned results, everything works as expected.

When calling same code from above, but with **field.countDistinct()**, there are **no results returned**, empty list. When I inspect and get generated query, **I can execute it raw and I actually get results, as query looks like it should and returns what is should return**. 

```
query
.distinct()
.where(field.in(values))
.groupBy(id)
.groupBy(groupByField)
.having(field.countDistinct().goe(1))
```

Generated query when inspecting :
```
select distinct entity
where field in ( ... )
group by id, groupByField
having count(distinct field) >= 1
```

This query returns results, but blaze itself returns empty list, or exception, depending on version.

### Environment

Version:  1.6.0 (blaze-persistence-core-api, blaze-persistence-core-impl, blaze-persistence-integration-hibernate-5.4, blaze-persistence-integration-querydsl-expressions)
JPA-Provider:   Hibernate 5.4.23    
DBMS:               MySql 8.x
Application Server: Tomcat

**Comment by alohaaloha** [comment] 2021-11-04 20:54
@jwgmeligmeyling @beikov 

I have pure querydsl query that was executing in about 10sec. I replaced that with blazebit querydsl and now query takes 1.5min 😭

**Comment by beikov** [comment] 2021-11-04 21:01
You have to give us some more details if you want help. There is no reason for such queries to be slower in general. Please post the two SQL queries and the corresponding QueryDSL queries so we can analyze this

**Comment by beikov** [comment] 2021-11-04 21:14
There could literally be anything hidden behind these three dots...

Please post the actual SQL queries that are executed. Without that, any speculation is pointless.

**Comment by alohaaloha** [comment] 2021-11-04 21:19
That is the same query I was working when opening this bug: `group by + having + count + distinct`

Hope this is useful: 
```
select distinct store from Store store
left join Point point on point.store_id = store.id 
where point.type = ?1
group by store.id
having count(distinct point.type) >= 1;
```

**Comment by beikov** [comment] 2021-11-04 21:26
Ok so which SQL query is that. The one you see with or without blaze-persistence? How does the other one look like?

**Comment by jwgmeligmeyling** [comment] 2021-11-05 10:03
`Fetch is ignored due to on-clause` indicates that you're requesting a fetch join, which is ignored if the join specifies an on predicate. Perhaps you are now relying on lazy loading of these associations after the query has executed instead? Although I doubt that this type of fetch join would have been allowed in standard Querydsl anyway.

**Comment by alohaaloha** [comment] 2021-11-05 16:12
Both generated queries are the same. Problem regarding to speed was because 'Store' entity has many complex fields in it.

After changing quedydsl from:

select distinct store from Store store
left join Point point on point.store_id = store.id 
where point.type in ?1
group by store.id
having count(distinct point.type) = 3;

to 

select distinct store.id from Store store
left join Point point on point.store_id = store.id 
where point.type in ?1
group by store.id
having count(distinct point.type) = 3;

speed went down fully.


On querydsl - from 10sec to 0.2 sec
On blazebit - from 40sec to 0.2 sec

**Comment by jwgmeligmeyling** [comment] 2021-11-05 16:33
Can you compare the produced SQL queries for both original queries?

Both queries should produce the exact same SQL (its Hibernate generating the SQL for the JPQL query in the end, not Querydsl or Blaze-Persistence) and therefore the performance finding is very surpsing and somewhat unbelievable.

My intuition would be that unnessairy join nodes are added to the query leading to a poorer query execution plan being chosen by the DB.

I do assume you're measuring just the query time, not bootstrap performance?

**Comment by alohaaloha** [comment] 2021-11-05 16:38
Both generated queries are the same.

No, raw query executed directly on database is fast, those times are when measuring query execution + bootstap performance, so executing it via `query.fetch()`

**Comment by beikov** [comment] 2021-11-05 17:44
>Both generated queries are the same. Problem regarding to speed was because 'Store' entity has many complex fields in it.

This is a problem in your query/database i.e. obviously it will be faster for the database to determine distinctness just based on the primary key than for a bunch of attributes. But you write the query, so it's in your power to change it.

>Both generated queries are the same when using querydsl and blazebit (query posted above)

If both queries are the same, the execution time has to be "the same" as well.

>Difference in speed is when executing it in code.
>Those times are when measuring query execution + bootstrap performance, in code, so executing it via query.fetch()

I don't know what you mean by "boostrap performance" but there is some cost in the building of the metamodel for Blaze-Persistence, although I highly doubt that it takes 30 seconds to build, unless you have 1000+ entities.

Can you please share what it is that you are "benchmarking" and also how you are doing that so we can better understand this?

**Comment by alohaaloha** [comment] 2021-11-05 19:18
Let's start again.

```
var results = query
.select(qStore)
.from(qStore)
.leftJoin(qPoints).on(qPoints.storeId.eq(qStore.id)
.where(qPoints.type.in(_SOME_VALUES_))
.groupBy(qStore.id)
.having(qPoints.type.countDistinct().goe(1))
.fetch():
```

When I write following using **querydsl**, it takes **10seconds** to **to get results**.

When I write the same, but using **querydsl with blazebit support**, it takse **40seconds** to **get the results**.

When I turn hibernate logs, or print query.toString, I see exactly the same generated 'sql' in both cases.

When I copy that generated 'sql' into db, query get results basically instantly.

Returned size is around 1100 entities, heavy entities.

So, i switched from 
.select(qStore) to select(qStore.id) and now to get results, using querydsl, it takes basically no time.

**Comment by beikov** [comment] 2021-11-05 19:24
Well, it is expected that fetching entities takes a bit more time, as Hibernate has to construct entities etc. The fact that the query seems to be executed instantly doesn't mean it will be as instant if you actually fetch all data. Many SQL clients don't fetch the whole result set like Hibernate does. If you actually fetch all the data you might see more time spent in your plain SQL case as well.

What is the bootstrap time you referred to before?

**Comment by alohaaloha** [comment] 2021-11-05 19:27
I was referring to the time it takes hibernate to actually populates entities.

**Comment by beikov** [comment] 2021-11-05 19:31
It makes no sense to me why this would take longer with Blaze-Persistence. It is generating the same query and Blaze-Persistence does not fiddle with the result at all, it is completely generated by Hibernate.
I need to debug the actual code to understand that this better. If you want, yoh can attach a flamegraph and I can look into this, but a reproducer would be best.

**Comment by beikov** [comment] 2021-11-21 21:57
Is there anything else you can provide us here so we can analyze this? If not, I'm afraid there is not much we can do to help you.

**Comment by alohaaloha** [comment] 2021-11-22 21:25
Regarding to speed, I don't have any more info, as I just switched libraries without any changes in code, and that caused performance issues, as I stated above. And cleary my model is too heavy, with lots of properties that need to be fetched. That is fixed using smaller projection.

Regarding my initial problem, I notice that I had multiple group by statements:
var results = query
.select(qStore)
.from(qStore)
.leftJoin(qPoints).on(qPoints.storeId.eq(qStore.id)
.where(qPoints.type.in(_SOME_VALUES_))
.groupBy(qStore.id).groupBy(qPoints.storeId) // <--------- when i removed second groupBy, everything worked as expected
.having(qPoints.type.countDistinct().goe(1))
.fetch():

**Comment by beikov** [comment] 2021-11-23 07:55
>... I just switched libraries without any changes in code, and that caused performance issues, as I stated above, no other changes are done.

The comments you posted seem to suggest that there is something different going on.

>In logs, there is only: Fetch is ignored due to on-clause

I think that with plain QueryDSL, different SQL is executed which might very well be the case, but so far you didn't show us the _original SQL statements_ that were execute for us to understand this properly. My guess is, that prior to switching, you had code like this:

```
QStore qStore = QStore.store;
new JPAQueryFactory(getEntityManager()).selectFrom(qStore)
.select(qStore)
.distinct()
.from(qStore)
.leftJoin(qPoints).on(qPoints.storeId.eq(qStore.id)
.where(qPoints.type.in(_SOME_VALUES_))
.groupBy(qStore.id)
.having(qPoints.type.countDistinct().goe(1))
.fetch():
```

which results in 2 SQL statements similar to this:

```
select distinct store.id 
from Store store
left join Point point on point.store_id = store.id
where point.type in ?1
group by store.id
having count(distinct point.type) >= ?
```

and

```
select *
from Store store
where store.id in (?, ?, ?, ...)
```

Whereas with Blaze-Persistence you have this code:

```
QStore qStore = QStore.store;
new BlazeJPAQuery<>(getEntityManager(), criteriaBuilderFactory)
.select(qStore)
.distinct()
.from(qStore)
.leftJoin(qPoints).on(qPoints.storeId.eq(qStore.id)
.where(qPoints.type.in(_SOME_VALUES_))
.groupBy(qStore.id)
.having(qPoints.type.countDistinct().goe(1))
.fetch():
```

which results in just 1 SQL statement similar to this

```
select distinct store.*
from Store store
left join Point point on point.store_id = store.id
where point.type in ?1
group by store.*
having count(distinct point.type) >= ?
```

I can totally understand why this single SQL query is slower than the two others and we can adapt the behavior to match up what plain QueryDSL does, but we really need to know the details first before we can do anything.

@jwgmeligmeyling do you know of any such transformations? The log information seems to suggest something like this.

**Comment by jwgmeligmeyling** [comment] 2022-02-21 18:57
```java
BlazeJPAQuery<Tuple> query = new BlazeJPAQuery<>(em, cbf)
        .from(person)
        .leftJoin(person.favoriteDocuments, document)
        .groupBy(person.id, person.friend.id)
        .select(person.id, document.countDistinct())
        .where(document.id.in(1l, 2l, 3l))
        .having(document.id.countDistinct().gt(1));
```

Produces:

```
SELECT person.id, COUNT(DISTINCT document) FROM Person person LEFT JOIN person.favoriteDocuments document WHERE document.id IN (:param_0) GROUP BY person.id, person.friend.id HAVING COUNT(DISTINCT document.id) > :param_1
```

So:

* Distinct correctly passed to count function
* Multiple group by does not mess with the count distinct or the having clause

The produced SQL:
```sql
select person0_.id as col_0_0_, count(distinct document2_.id) as col_1_0_ from person person0_ left outer join person_favorite_documents favoritedo1_ on person0_.id=favoritedo1_.Person_id left outer join document document2_ on favoritedo1_.favoriteDocuments_id=document2_.id where document2_.id in (? , ? , ?) group by person0_.id , person0_.friend_id having count(distinct document2_.id)>?
```

So:

* All three values are included in the query as parameters.

There is no transformation in Querydsl nor the integration with regard to the values clause or splitting a query in multiple queries. In fact the entire query serialization is quite transparent and as-is.

I cannot reproduce any other issue but the version mismatch from the original post.

**Comment by beikov** [comment] 2022-02-22 09:42
@alohaaloha: If you can provide us a reproducer or at least more details like the full entity model and actual executable code we can look into this more deeply, but as it is right now, we just couldn't reproduce your issue, so I'm going to close the issue.

**Closed by beikov** 2022-02-22 09:42 UTC
Labels: question, component: QueryDSL
