### ISSUE TITLE
JPA repositories no longer seem to work since 204117e

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1637] opened 2022-11-21 22:36 UTC
We used `204117e` without any test issues, but with the current stable release of `1.6.8` on of our (rare) JPA repositories no longer seem to work

```java
@Repository
interface DwCacheApiRepository extends JpaRepository<DwCacheApiEntry, Long>
{
  void deleteByCidStartsWith(String cid);

  Optional<DwCacheApiEntry> findByCid(String cid);
}
```

used like

```java
 dwCacheApiRepository.deleteByCidStartsWith("db_username_cache_uc_");
```

and then suddenly

```java
    assertThat(dwCacheApiRepository.findByCid("db_username_cache_uc_green")).isEmpty();
```

is no longer empty with 1.6.8 - anything changed in particular?

**Comment by beikov** [comment] 2022-11-23 10:54
Duplicate of https://github.com/Blazebit/blaze-persistence/issues/1638

**Closed by beikov** 2022-11-23 10:54 UTC
