### ISSUE TITLE
EntityViewRepository returns duplicate items for list associations defined within @EntityView models

### ISSUE THREAD

**Issue by Elgarni** [Blazebit/blaze-persistence#660] opened 2018-09-13 17:52 UTC
### Description
`@EntityView` annotated interfaces with multiple list associations to other `@Entity` annotated model-classes will return duplicate items within those list associations in some cases.

Here is an example to illustrate the issue. The example shows a `Movie`, that is associated to many `Genre`s, and to many `Cast` members.
#### _Model Classes_ 

```java
@Entity
@Table(name = "genres")
public class Genre {

    @Id
    @GeneratedValue
    private int id;
    private String name;

    // getters & setters
}
```

```java
@Entity
@Table(name = "casts")
public class Cast {
    @Id
    @GeneratedValue
    Integer id;
    private String gender;
    private String name;
    
    // getters and setters
}
```

```java
@Entity
@Table(name = "movies")
public class Movie {
    @Id
    @GeneratedValue
    private Integer id;

    private String title;
    private String overview;
    private String releaseDate;

    @ManyToMany
    @JoinTable(name = "movies_genres",
            joinColumns = { @JoinColumn(name = "movie_id") },
            inverseJoinColumns = { @JoinColumn(name = "genre_id") })
    private List<Genre> genreList ;

    @ManyToMany
    @JoinTable(name = "movies_cast",
            joinColumns = { @JoinColumn(name = "movie_id") },
            inverseJoinColumns = { @JoinColumn(name = "cast_id") })
    private List<Cast> castList;
// Getters & Setters
}
```
#### _Entity View Models_

```java
@EntityView(Movie.class)
public interface MovieView {
    @IdMapping
    Integer getId();

    List<Genre> getGenreList();

    List<Cast> getCastList();
}
```

#### _Repository_

```java
@Repository
public interface MovieViewRepository extends EntityViewRepository<MovieView,Integer> {
}
```

#### Database tables

`genres` table

 id                 |     name       |
 ------------- | ------------- |
 1 | Action  |
 2 | Drama  |
 3 | Fantasy |
 4 | Thriller  |

`casts` table

 id                 |     name       |   gender
 ------------- | ------------- |   --------
 1 | Will | male
 2 | Liza  | Female

`movies` table

 id                 |     overview  |   release_date |  title
 ------------- | ------------- |   -------------  | ------
 1 | some overview about movie 1| 2018    | The first

`movies_cast` table

 movie_id |     cast_id |
 ------------- | ------------- |
 1 | 1|

`movies_genres` table

 movie_id |     genre_id |
 ------------- | ------------- |
 1 | 2|
 1 | 3

### Actual behavior

When calling `findAll()` from `EntityViewRepository`, the response is returned as follows (_serialized to json_) : 
```json
[
    {
        "id": 1,
        "castList": [
            {
                "id": 1,
                "gender": "Male",
                "name": "Will"
            },
            {
                "id": 1,
                "gender": "Male",
                "name": "Will"
            }
        ],
        "genreList": [
            {
                "id": 2,
                "name": "Drama"
            },
            {
                "id": 3,
                "name": "Fantasy"
            }
        ]
    }
]
```
The cast list item object is duplicated.

### Expected behavior
The correct response should be as follows : 

```json
[
    {
        "id": 1,
        "castList": [
            {
                "id": 1,
                "gender": "Male",
                "name": "Will"
            }
        ],
        "genreList": [
            {
                "id": 2,
                "name": "Drama"
            },
            {
                "id": 3,
                "name": "Fantasy"
            }
        ]
    }
]
```
It is worth noting that when calling `findAll()` from **`JpaRepository`**, this expected result is what gets returned.

### Steps to reproduce
The parts mentioned above summarize the steps to re-produce such issue.

It is important to note that this issue does not occur in the following scenarios : 

- The _**EntityView**_ has only one list association
- The _**EntityView**_ has several list associations, but all have either one or zero elements.

So to reproduce the issue, keep in mind that you need to have more than one list association in the `@EntityView`-annotated interface, one of each must have more than one element and the rest should have at least one element. 

### Environment
I encountered the issue while developing a SpringBoot project, with the following _gradle_ dependencies:

```gradle
dependencies {
    compile "com.blazebit:blaze-persistence-integration-spring-data-2.x:1.2.1"
    compile "com.blazebit:blaze-persistence-integration-hibernate-5.2:1.2.1"
    // other dependencies 
}
``` 

**Version**:  1.2.1          
**JPA-Provider**:  Spring Data / Hibernate 5
**DBMS**:  PostgreSQL 9.5 ( _less likely to be the problem_)
**Application Server**: Tomcat ( _less likely to be the problem_)

**Comment by beikov** [comment] 2018-09-13 17:59
The problem is that the list is interpreted as a bag although it could be internally treated like a set. I'll look into this and get this fixed for the final release.

**Comment by beikov** [comment] 2018-09-13 18:00
Have you tried using entity views for `Genre` and `Casts` as well?
Maybe this is related to the use of entity types.

**Comment by Elgarni** [comment] 2018-09-13 20:07
I've just tried with entity views for  `Genre` and `Cast`, but still the response contains duplicate.  

Here is the new Entity Views:

```java
@EntityView(Genre.class)
public interface GenreView {
    @IdMapping
    Integer getId();

    String getName();
}
```

```java
@EntityView(Cast.class)
public interface CastView {
    @IdMapping
    Integer getId();

    String getName();
}
```

Changing the `MovieView` to use them :
```java
@EntityView(Movie.class)
public interface MovieView {
    @IdMapping
    Integer getId();

    List<GenreView> getGenreList();

    List<CastView> getCastList();
}
```

The response for `findAll()` ; 
```json
[
    {
        "id": 1,
        "castList": [
            {
                "id": 1,
                "name": "Will"
            },
            {
                "id": 1,
                "name": "Will"
            }
        ],
        "genreList": [
            {
                "id": 2,
                "name": "Drama"
            },
            {
                "id": 3,
                "name": "Fantasy"
            }
        ]
    }
]
```

The new Entity Views took effect in `MovieView`, as `genreList` shows. However, the result still contains duplicate items.

**Comment by Elgarni** [comment] 2018-09-14 19:20
Good to hear. Looking forward to 1.3 release.

**Comment by beikov** [comment] 2018-09-14 19:28
But regardless of that, I'd recommend you use a different fetch strategy for one of the collections. That way you avoid a big cross product and workaround your issue

**Comment by beikov** [comment] 2018-09-17 08:00
Fixed by f284bce0bd34f2d73bd073e780d294383d5e9552

**Closed by beikov** 2018-09-17 08:00 UTC
Labels: bug, entity-view

**Comment by lmbuchholz** [comment] 2024-11-03 17:14
Hi @beikov, I am facing this issue with Spring Boot 3.3.3/Spring Data JPA/Hibernate 6. My program and database structure is almost identical to the above, the only difference being that I am using Maven, objects are not getting serialized to JSON, and my composite tables use surrogate IDs like so: 

movies_cast table
movie_cast_id | movie_id | cast_id
-- | -- | --
1 | 1 | 1

movies_genres table
movie_genre_id | movie_id | genre_id
-- | -- | --
1 | 1 | 2
2 | 1 | 3

I am using entity views to fetch all collections like mentioned in the later [comment](https://github.com/Blazebit/blaze-persistence/issues/660#issuecomment-421135891) above. All classes are implementing equals and hashcode methods through Lombok.

Could you kindly confirm if this issue is present in Blaze Persistence version 1.6.12?

**Comment by beikov** [comment] 2024-11-05 18:17
@lmbuchholz please create a new issue with more details about your case.

**Comment by lmbuchholz** [comment] 2024-11-28 04:11
@beikov, please see issue [1961](https://github.com/Blazebit/blaze-persistence/issues/1961)
